std = "roblox"

[rules]
parenthese_conditions = "allow"
unused_variable = "allow"
shadowing = "allow"
global_usage = "allow"

[config]
empty_if = { comments_count = false }
unused_variable = { allow_unused_self = true }